// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIjKRttnKNMgPk5s8kvfeOo_DkR_PiPxM',
    appId: '1:783963393864:web:c5b09e1d60a6ae0530ed7d',
    messagingSenderId: '783963393864',
    projectId: 'strayanimalsapp',
    authDomain: 'strayanimalsapp.firebaseapp.com',
    storageBucket: 'strayanimalsapp.appspot.com',
    measurementId: 'G-QJ4C7L9L7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ_GemZAfYWec9QLhTa733ACvvfgG4iZo',
    appId: '1:783963393864:android:36c5e8c79301ca4330ed7d',
    messagingSenderId: '783963393864',
    projectId: 'strayanimalsapp',
    storageBucket: 'strayanimalsapp.appspot.com',
  );
}
